name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        target: ${{ matrix.target }}
        default: true
        override: true
    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
      
