name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        cargo_target:
          - x86_64-apple-darwin
          

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
      
